version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "Test"
      POSTGRES_USER: "postgres"
      POSTRGES_PASSWORD: "postgres"
    ports:
     - "5432:5432"
